### PR TITLE
fixed some linting errors

### PR DESCRIPTION
**Pull request by olumide-AI**
Fixed some linting errors i could find on the communication documentation

### CODE REVIEW

**Review by suhrobmuboraksho — APPROVED** [review]
Looks good!

**Review by suhrobmuboraksho — CHANGES_REQUESTED** [review]
You have to first update your "main" branch locally with the changes that I committed yesterday first (which you reviewed for "Pull Request"). **Manezha has to approve and merge it first**. Then you pull the fresh "communication" file onto your computer, make the changes and then push to your branch.

**Review by yuri-spizhovyi-mit — APPROVED** [review]

**Review by olumide-AI — COMMENTED** [review]
How can i approve this changes, I believe they fix the markdown errors

**Comment by Khadijaramlawi** [comment]
Hi @olumide-AI , Thanks for asking. You can approve it by clicking on the add to review button at the top right corner in the page, and then finish your review by approving it from the list showed in the second screenshot. You can approve it directly or by adding comments. Some colleagues have posted videos on this matter in CD slack group, I'll tag you if I find it. Please let me know if you are still unable to approve it, I'm happy to help
Screenshot 2024-12-28 at 11 32 56 AM
Screenshot 2024-12-28 at 11 32 32 AM

**Review by suhrobmuboraksho — APPROVED** [review]
Reviewed after merging the conflicts

**Review by yuri-spizhovyi-mit — APPROVED** [review]

**Pull request merged**
