### PR TITLE
Edited the template for the communication.md file.

### PR DESCRIPTION
**Pull request by suhrobmuboraksho**
Please review and commit your time preferences in the file.

### CODE REVIEW

**Review by Alemayehu-Desta — APPROVED** [review]
added my available time

**Comment by suhrobmuboraksho** [comment]
My understanding is that, "Reviewers" have to review and put comments regarding my file edits, not directly editing the file here. If you want to edit the file , it has not to be done here, but rather create your branch locally -> commit -> push -> create a "Pull Request". We have to discuss it in our meeting.

**Comment by suhrobmuboraksho** [comment]
Please review the changes I made to the file after merging @olumide-AI initial commit to the file.

**Review by olumide-AI — APPROVED** [review]
I believe this changes look good to me.

**Review by Khadijaramlawi — APPROVED** [review]

**Review by yuri-spizhovyi-mit — APPROVED** [review]
Approved

**Review by Manezhahm — COMMENTED** [review]
good

**Review by Manezhahm — COMMENTED** [review]
good

**Pull request merged**
