### PR TITLE
Root readme khadija

### PR DESCRIPTION
**Pull request by Khadijaramlawi**
---
name: solution review 
about: A template PR for code review with a checklist
---

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

### CODE REVIEW

**Review by olumide-AI — COMMENTED** [review]
Most changes looks great to me, Khadija added her learning goals, availability, changed the deadline for the projects,

I'm curious khadija, why was the changes made tot he solution tree? I'm just trying to understand what was wrong with the old tree or why you think the new format is better. Thank you

**Comment by Khadijaramlawi** [comment]
Thanks @olumide-AI for your feedback! I did it because we have asked Evan on slack if it's suitable to structure the solution tree as the old way and this was his response: "I would suggest doing it like in the examples and exercises folders.   Someone using your code would want to know what it does, not who wrote it.    It’s still possible to know who wrote what by reading through the git/github history: /solutions
  /tests
    test_deep_flatten_list.py
    test_find_largest.py
  deep_flatten_list.py
  file_largest.py" 
  I hope it's clear now for you, please let me know if you'd like to discuss this issue further.

**Review by olumide-AI — DISMISSED** [review]

**Review by Alemayehu-Desta — COMMENTED** [review]
I have to change my schedule in the READMe and Communication file.

**Review by Papsik09 — COMMENTED** [review]
Couldn't understand what are the changes in README.md . What are they for?

**Comment by Papsik09** [comment]
> Couldn't understand what are the changes in README.md . What are they for?

Didn't see the comments above from Khadija. I understnd now what for. :)

**Review by Papsik09 — DISMISSED** [review]

**Review by yuri-spizhovyi-mit — APPROVED** [review]
Great job! Approved.

**Review by yuri-spizhovyi-mit — APPROVED** [review]

**Review by yuri-spizhovyi-mit — APPROVED** [review]

**Review by yuri-spizhovyi-mit — APPROVED** [review]

**Review by yuri-spizhovyi-mit — DISMISSED** [review]

**Review by yuri-spizhovyi-mit — DISMISSED** [review]

**Pull request closed without merging**
