### PR TITLE
Creation of README.md draft

### PR DESCRIPTION
**Pull request by Mykytako**
---
name: solution review 
about: A template PR for code review with a checklist
---

### Files

- [x] The file name describes the function's behavior
- [x] There is a module docstring in the function file
- [x] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

### CODE REVIEW

**Comment by Papsik09** [comment]
This README.md supposed to have our team name and small overview for our project. 

Instead, we should put this draft inside [collaboration/README.md]

Screenshot 2024-12-24 101811

**Comment by Papsik09** [comment]
This README.md is used for our team name and overview on project based on 0_repository_setup.md
   - Update your main README with your group name and an initial overview of your project. (You can change this as much as you want.)

Instead, we should put this inside different README.md based on information from 1_group_norms.md 
   -Complete the Group Norms assignment from the Code Review workshop and write your norms summary and list in the [Collaboration README](https://github.com/MIT-Emerging-Talent/ET6-foundations-group-01/blob/ee5e28037d367339e62f10a367be487cd55a0ecb/collaboration/README.md) 

To access the right README.md use path [collaboration\README.md]

Screenshot 2024-12-24 101811

**Review by Alemayehu-Desta — COMMENTED** [review]
Hello @Mykytako,
Thank you for pulling the file. My understanding is the README file is about the overall description of the group project. The Group norm should be inside the collaboration file. Let's talk about it if I am missing something! Thank you

**Comment by suhrobmuboraksho** [comment]
The top-level README.md file should be about the group description. The README.md file inside collaboration is about the group norms.

**Comment by Mykytako** [comment]
Thanks for the correction guys! Sorry for the mistake, I'll close this PR then

**Comment by Khadijaramlawi** [comment]
Hi Mykytako. As the team mentioned,  the group norms should be written in the Readme file as shown below. The file has minimal comments and we have to fill it. Thanks for raising this issue, I was confused about it and had to rewatch the recording to make sure we're writing the norms in the right location.
Screenshot 2024-12-24 at 12 04 52 PM

**Pull request closed without merging**
